import Axios from 'axios'
import dynamic from 'next/dynamic'
import React, { useEffect, useContext } from 'react'
import MasterVol from '../components/controls/MasterVol/MasterVol'
import MasterBPM from '../components/controls/MasterBPM/MasterBPM'
import Navbar from '../components/Navbar/Navbar'
import styles from '../styles/Home.module.scss'
import Cube from '../components/Cube/Cube'
import { CTX } from '../context/Store'

const Keyboard = dynamic(() => import('../components/Keyboard/Keyboard'), { ssr: false })

function Home() {
  const [, updateState] = useContext(CTX)

  useEffect(() => {
    let subscribed = true

    if (subscribed) {
      const foundToken = localStorage.getItem('fmsynth-token')

      if (!foundToken) {
        updateState({
          type: 'LOGOUT',
        })

        //rotate to auth
        updateState({
          type: 'CHANGE_ROTATION',
          payload: `rotate3d(100, 0, 0, 270deg)`,
          page: 'auth',
        })
      } else {
        const setAuthInfo = async () => {
          Axios.get('/auth/user', {
            headers: { 'x-auth-token': foundToken },
          })
            .then((result) => {
              if (!result.data.err) {
                updateState({
                  type: 'LOGIN',
                  payload: { user: result.data, token: foundToken },
                })
              } else {
                console.log('err: ', result.data.err)
              }
            })
            .catch(() => {
              updateState({
                type: 'LOGOUT',
              })
            })
        }
        setAuthInfo()
      }
    }

    return () => {
      subscribed = false
    }
  }, [updateState])

  return (
    <div className="App">
      <Keyboard />
      <Navbar />
      <Cube />
      <div className={styles.hiddenMasters}>
        <MasterVol />
        <MasterBPM />
      </div>
    </div>
  )
}

export default Home

// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
